fetch("http://localhost/zero-waste-city-demo/dbconnect/barGraphData.php").then(function(response){
  return response.json();
}).then(function(obj){
    console.log(obj);
    var barChart = new CanvasJS.Chart("barChart", {
        animationEnabled: true,
        theme: "light2",
        title:{
          text: "Waste generated by Countries"
        },
        axisY: {
          title: "Waste produced (in tonnes)"
        },
        data: [{
          type: "column",
          yValueFormatString: "#,##0.## tonnes",
          dataPoints: obj
        }]
    });
    
    barChart.render();
}).catch(function(error){
  console.error(`Oops error occured: ${error}`);
});

fetch("http://localhost/zero-waste-city-demo/dbconnect/multiLineGraphData.php").then(function(response){
  return response.json();
}).then(function(obj){
    console.log(obj);
    var mulChart = new CanvasJS.Chart("multiLineChart", {
        animationEnabled: true,
        theme: "light2",
        title:{
          text: "Waste generated by Countries"
        },
        axisY: {
          title: "Waste produced (in tonnes)"
        },
        data: [{
          type: "line",
          yValueFormatString: "#,##0.## tonnes",
          dataPoints: obj
        }]
    });
    
    mulChart.render();
}).catch(function(error){
  console.error(`Oops error occured: ${error}`);
});