// Inserting the JSON file

fetch("http://localhost/zero-waste-city-demo/dbconnect/multiLineGraphData.php").then(function(response){
  return response.json();
}).then(function(obj){
  drawGraph(obj);
}).catch(function(error){
  console.error(`Oops error occured: ${error}`);
});

function drawGraph(jsonObj){
  var mulChart = new CanvasJS.Chart("barGraph", {
      animationEnabled: true,
      theme: "light2",
      title:{
        text: "Waste generated by Countries"
      },
      axisY: {
        title: "Waste produced (in tonnes)"
      },
      data: [{
        type: "area",
        yValueFormatString: "#,##0.## tonnes",
        dataPoints: jsonObj
      }]
  });
  
  mulChart.render();
}